# Generated by Django 5.2 on 2026-05-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
