# Generated by Django 5.2 on 2026-05-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='tasa_interes',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='categorias',
            field=models.ManyToManyField(related_name='prestamos', to='loans.categoria'),
        ),
    ]
